### PR TITLE
[WIP] Add Plan Wizard: Split resources into src, dst and replication

### PR DESCRIPTION
**Pull request by gildub**
WIP - Please DO NOT MERGE.

animation

Closes https://github.com/konveyor/mig-ui/issues/724
Closes https://github.com/konveyor/mig-ui/issues/765

### CODE REVIEW

**Comment by gildub** [comment]
@vconzola, please let me know what you think.

**Comment by mturley** [comment]
@vconzola your other reasons to hold off are valid, and @gildub we should communicate better so we don't step on each other's toes, but luckily I think this would not conflict with the stuff I'm working on for the PV and Storage Class wizard steps, since we're working in different files.

**Comment by eriknelson** [comment]
>  I'd also like to make these changes at the same time we're addressing changes to be able to scale the UI to handle large numbers of namespaces #426.

@vconzola It's unlikely we're going to touch #426 until 1.3, certainly it's post-1.2.0.

Are we sure we want to wait until we're moving into June to split out this screen?

**Comment by vconzola** [comment]
@eriknelson Yes, I'd prefer to wait. As implement it would add two steps to the wizard, which with the hooks would mean we'd have an 8 step wizard and three of the first four steps would have only a single input field. I'd rather take some time and understand what fields can be combined in a step in way that makes sense from both a UX and controller standpoint. Also, the wizard works as is and we don't need to break the steps out until we tackle #426, so I think we should do them together.

**Comment by eriknelson** [comment]
@vconzola ACK, makes sense.

@gildub Going to close this PR; I don't think there's going to be a lot here that can be reused and we're going to take a step back from a design standpoint and revisit this in a couple months.

**Pull request closed without merging**
