### PR TITLE
Bug 2011508: making description for cutover migration more accurate

### PR DESCRIPTION
**Pull request by JaydipGabani**

### CODE REVIEW

**Review by rayfordj — APPROVED** [review]

**Review by vconzola — CHANGES_REQUESTED** [review]
@JaydipGabani Per Scott's suggestion further down in the Slack thread, can you also change the word "transactions" to "applications" in this PR. Tx.

**Comment by mturley** [comment]
This will conflict with https://github.com/konveyor/mig-ui/pull/1368 where we overhauled this modal based on migration type. The new text there for full migration cutovers is "By default, all transactions on the source cluster are halted for the duration of the migration.". @vconzola what should the text be considering both requirements? (more concise, but mentioning the namespaces). You can click on "files changed" above to see the old and new phrasing for this PR.

**Review by mturley — CHANGES_REQUESTED** [review]
Per @vconzola we plan to handle this in https://github.com/konveyor/mig-ui/pull/1368 if that's ok with you @JaydipGabani

**Comment by mturley** [comment]
Closing, change incorporated into https://github.com/konveyor/mig-ui/pull/1368/commits/4a39bf32f024771d39eb4006a812f2625b298252

**Pull request closed without merging**
