### PR TITLE
Update table status for current cluster

### PR DESCRIPTION
**Pull request by ibolton336**
Update cluster status in table view when cluster is actively being added or changed. This fixes the bug where the previous cluster status would show before the edit or add was finished.

### CODE REVIEW

**Comment by ibolton336** [comment]
https://user-images.githubusercontent.com/11218376/117154908-52223e00-ad8a-11eb-97bc-0f0ec5a950fe.mov

**Comment by djwhatle** [comment]
Trying this out!

**Review by djwhatle — APPROVED** [review]
LGTM. Made a change to my MigCluster, saw it go from pending -> error state.

**Comment by vconzola** [comment]
LGTM too.

**Pull request merged**
