### PR TITLE
Add error handling for rbac issue/critical conditions when migrating

### LINKED ISSUE #661: Unhandled error when attempting a stage
Screen Shot 2020-02-06 at 8 30 52 AM
Screen Shot 2020-02-06 at 8 32 56 AM

### PR DESCRIPTION
**Pull request by ibolton336**
Closes #661 

Screen Shot 2020-02-06 at 10 26 49 AM

### CODE REVIEW

**Comment by eriknelson** [comment]
@vconzola

**Comment by eriknelson** [comment]
Marking do-not-merge until @vconzola has had a chance to ack. I know he's taking a bit of PTO so it may be a little bit before this can be merged.

**Comment by vconzola** [comment]
@eriknelson @ibolton336 Rather than showing the verbose message in the status field of the list, we should show the status for the migration as "Failed" and add an inline notification with the detailed error message. I'll mock something up in the next day or so.

**Comment by eriknelson** [comment]
Ack, thanks @vconzola. Going to put a DNM on this until we get back those mocks and make the requested changes.

**Comment by vconzola** [comment]
@ibolton336 Here's a mockup showing how we should handle errors that occur during stage/migration. A couple of notes:

- Use inline alerts (https://www.patternfly.org/v4/documentation/react/components/alert). They will stack and push down the page content (this is not shown in the mockup).
- If possible, we should include a link to the migration log file (should open in new tab). If it's not possible, just ignore this in the mockup.
failed stage

**Comment by ibolton336** [comment]
> @ibolton336 Here's a mockup showing how we should handle errors that occur during stage/migration. A couple of notes:
> 
> * Use inline alerts (https://www.patternfly.org/v4/documentation/react/components/alert). They will stack and push down the page content (this is not shown in the mockup).
> * If possible, we should include a link to the migration log file (should open in new tab). If it's not possible, just ignore this in the mockup.
>   failed stage

Great idea, VInce. I think we should open a new issue to add alerts for migration/stage failure/sucess with more detailed error info. This particular error is significantly longer than the rest of the error states. I think it would make sense for a more thoughtful implementation of this functionality. For the scope of this PR, I propose that we just show a shorter message & fix the hung "in progress" state.

**Comment by ibolton336** [comment]
#674

**Comment by eriknelson** [comment]
Think this needs a rebase now that we brought in the SASS modules PR.

**Comment by ibolton336** [comment]
> Think this needs a rebase now that we brought in the SASS modules PR.

Rebased

**Comment by eriknelson** [comment]
This is an incremental improvement working towards @vconzola's overall mockup, and #674 properly captures the desired long term work in an issue. Think we want to accept this and continue to work 674.

**Pull request merged**
