### PR TITLE
Tree improvements: 404 fix & tree console fix

### PR DESCRIPTION
**Pull request by ibolton336**
- Handle 404 errors for debug Refs seperately from tree request errors
-  Fix warnings in console

### CODE REVIEW

**Comment by djwhatle** [comment]
Trying this out!

**Comment by djwhatle** [comment]
Seeing something a little funky going on with the spinners, not sure why.


https://user-images.githubusercontent.com/7576968/116734553-64cbfa00-a9bb-11eb-8b3d-d10cd0f943b0.mov

**Comment by djwhatle** [comment]
@ibolton336 I also just saw the UI crash when I started a stage migration.

**Comment by djwhatle** [comment]
@ibolton336 still seeing some weird stuff like the kebab menu popover auto-closing itself after a few second, coinciding with glitch to the spinner.


https://user-images.githubusercontent.com/7576968/116752748-03fceb80-a9d4-11eb-96f2-e491767da4d3.mov

**Comment by ibolton336** [comment]
> @ibolton336 still seeing some weird stuff like the kebab menu popover auto-closing itself after a few second, coinciding with glitch to the spinner.
> 
>  Screen.Recording.2021-04-30.at.4.48.41.PM.mov

This was a result of trying to roll a custom TreeView local to our project. Rolled back these changes so everything should be working now. 

https://github.com/patternfly/patternfly-react/pull/5730 opened upstream to address distracting key errors in the console

**Comment by djwhatle** [comment]
Still seeing the issue of the tree feeling like it is rebuilt from scratch every few seconds. For instance, seeing any elements that I collapse in the tree getting popped back open after 2 seconds or so.

**Comment by djwhatle** [comment]
@ibolton336 saw the page crash during cleanup of a direct migration while sitting in the debug tree view. Full log attached.

image


[localhost-1620233746393.log](https://github.com/konveyor/mig-ui/files/6428876/localhost-1620233746393.log)

**Review by djwhatle — APPROVED** [review]
Have run through multiple large migrations with no crashes 👍  ACK

**Pull request merged**
