### PR TITLE
Finish SCC / progressive wizard features: Add Stage and Cutover support for state migrations and storage class conversions, fix confirm modals and CR properties, misc UX tweaks

### PR DESCRIPTION
**Pull request by mturley**
Closes https://github.com/konveyor/mig-ui/issues/1362.

Implements all the remaining functionality issues and UX tweaks.

This PR also does a few other things:
* Updates the text in the confirmation modals for Stage, Cutover and Rollback actions based on the plan's migration type
* Makes sure the migration actions in the kebab menu are consistent in both the plans page and the migrations page on a particular plan. The code was previously duplicated between those and inconsistent, now it has been factored out into MigrationActionsDropdownGroup.
* Fixes a minor bug when editing PVs to change the target PVC name. In some cases, the new name you enter would not appear until reloading that wizard step. Now it will always appear properly.
* Fixes a corner case where sometimes the wizard could crash when being opened for editing in certain conditions.
* Refactors all references to the `migrateState`, `stage`, `quiescePods` and `rollback` properties on a Migration CR to use new helper functions `migSpecToAction` and `actionToMigSpec` that determine what action a migration is performing (or what spec properties should be on the migration for a given user action) based on this matrix:

| Migration Type / Action | `migrateState` | `stage` | `quiescePods`                  | `rollback` |
| ----------------------- | -------------- | ------- | ------------------------------ | ---------- |
| Full / Stage            | False          | True    | False                          | False      |
| Full / Cutover          | False          | False   | (user selection, default True) | False      |
| Full / Rollback         | False          | False   | False                          | True       |
| State / Stage           | True           | False   | False                          | False      |
| State / Cutover         | False          | False   | False                          | False      |
| State / Rollback        | False          | False   | False                          | True       |
| SCC / Stage             | True           | False   | False                          | False      |
| SCC / Cutover           | True           | False   | True                           | False      |
| SCC / Rollback          | False          | False   | False                          | True       |

# Screens

I'll include all screenshots related to the storage class conversion feature and progressive wizard to keep everything in one place, since this PR completes the feature changes.

## Migration plans page

Table includes new Type column and filter from https://github.com/konveyor/mig-ui/pull/1366 which can be "Full", "State", or "Storage class conversion" and shows its overflow in a tooltip:

Screen Shot 2022-01-12 at 12 39 38 PM

Screen Shot 2022-01-12 at 12 42 36 PM

Actions dropdown always includes migration actions Stage, Cutover and Rollback for all plan types, disabled when not applicable:

Screen Shot 2022-01-12 at 12 41 17 PM

### Migration confirmation modals

Full migration / Stage action:

Screen Shot 2022-01-12 at 12 46 39 PM

Full migration / Cutover action:

Screen Shot 2022-01-12 at 12 48 54 PM

State migration / Stage action:

Screen Shot 2022-01-12 at 12 50 03 PM

State migration / Cutover action:

Screen Shot 2022-01-12 at 12 50 23 PM

Storage class conversion / Stage action:

Screen Shot 2022-01-12 at 12 50 52 PM

Storage class conversion / Cutover action:

Screen Shot 2022-01-12 at 12 51 08 PM

Full or state migration / Rollback action:

Screen Shot 2022-01-12 at 12 52 07 PM

Storage class conversion / Rollback action:

Screen Shot 2022-01-12 at 1 21 03 PM

## Migrations page

Clicking through to the list of migrations on a plan, the dropdown there also includes those same consistent Stage, Cutover and Rollback actions. The Type column of the table will also now display Stage, Cutover or Rollback regardless of plan type.

Screen Shot 2022-01-12 at 12 43 28 PM

## Plan wizard

Steps vary by selected migration type:
* Full migration steps: General, Namespaces, Persistent volumes, Copy options, Migration options, Hooks.
* State migration steps: General, Namespaces, Persistent volumes, Copy options
* Storage class conversion steps: General, Namespaces, Persistent volumes

### General step (all migration types)

Screen Shot 2022-01-12 at 12 45 10 PM

Full migration selected (state migration shows the same options):

Screen Shot 2022-01-12 at 12 53 57 PM

Storage class conversion selected:

Screen Shot 2022-01-12 at 12 54 52 PM

### Namespaces step (full or state migration)

Screen Shot 2022-01-12 at 12 59 24 PM

### Namespaces step (storage class conversion)

Screen Shot 2022-01-12 at 1 00 09 PM

### PVs step (full migration)

Screen Shot 2022-01-12 at 1 12 02 PM

### PVs step (state migration)

Screen Shot 2022-01-12 at 1 03 07 PM

### PVs step (storage class conversion)

Screen Shot 2022-01-12 at 1 09 50 PM

### Copy options step (full migration)

Screen Shot 2022-01-12 at 1 13 48 PM

### Copy options step (state migration)

Screen Shot 2022-01-12 at 1 15 51 PM

### Migration options step (full migration)

No changes.

### Hooks step (full migration)

No changes.

### CODE REVIEW

**Comment by mturley** [comment]
Moving back to draft until issues are resolved:
* Cutover action remains disabled after running a Stage on state/SCC plans
* Migration type is incorrect in status messages and in the migrations table (running a Stage displays Cutover)

**Comment by mturley** [comment]
Note to self: we need to factor in the phrasing changes from https://github.com/konveyor/mig-ui/pull/1370 to the changes here. (https://bugzilla.redhat.com/show_bug.cgi?id=2011508)

**Review by apinnick — COMMENTED** [review]
LGTM

**Comment by apinnick** [comment]
@mturley Could you please post screenshots to make things easier for the TW to document?

**Comment by mturley** [comment]
@apinnick I've added screenshots above for all changes in this PR and earlier PRs related to the storage class conversion feature.

**Review by pranavgaikwad — APPROVED** [review]
LGTM

**Pull request merged**
