### PR TITLE
Debug view enhancements

### PR DESCRIPTION
**Pull request by ibolton336**
image
image

Closes https://github.com/konveyor/mig-ui/issues/1095

### CODE REVIEW

**Comment by ibolton336** [comment]
@vconzola

**Comment by eriknelson** [comment]
Feels like we need a little more info in that error message than just "PartiallyFailed".

One of the pains we've had is there is a wide scope of the possible things that could go wrong that would cause a "PartiallyFailed" condition to show up on a Backup or a Restore, and it's not easy to get the underlying cause (it's either buried in velero logs, one of potentially hundreds of restic pods, or isn't reported at all).  This is all below Velero, so it's not something that's in our direct control unless we added an enhancement to our fork of Velero, or worked upstream to improve this (we have a Jira to do exactly that in the future).

At the very least, it would be good for us to somehow convey this, and have some kind of a call to action that might assist a user in finding the underlying cause? @alaypatel07 @dymurray do you guys have any suggestions for how we can make this error message more useful until we can actually get Velero reporting the root cause?

**Review by eriknelson — CHANGES_REQUESTED** [review]
We need some additional polish on this, that tooltip looks unfinished in the screenshot. @alaypatel07 @dymurray @sseago @pranavgaikwad Do you guys have some suggestions for what error messages we should key off of on the conditions for these objects in the debug view to provide a little more information?

I'm hoping there's something like a field called `reason` or `message` on all conditions of type `warning` or `error` that we can key off of to do something like add the following text to the tooltip:

`An ${errorOrWarning} condition was found with the following message: ${condition.message}`

**Comment by ibolton336** [comment]
image


This is what we are able to see from the discovery service response ^^^

**Comment by djwhatle** [comment]
@eriknelson @ibolton336 

For the Mig* CRs, we make heavy use of conditions, but also consistently set the phase for MigMigration, DVM, DIM, and DISM. I think the Debug View could tally up the number of `Warning` and `Critical` conditions and show those tallies next to representative warn/error icons.

We should also show in the debug view if the phase of any of MigMigration, DVM, DIM, DISM are failed. The phase `MigrationFailed` is used across MigMigration, DVM, DIM, DISM to indicate failure.

It would also be helpful if the Debug view showed a spinner animation next to any "Running" CR such as MigMigration, DVM, DIM, DISM, Backup, Restore. This would help to focus the users attention on the currently active tasks. You could find out if a CR is running by looking for a "Running" condition on our MTC CRs. For Velero CRs you'd look for the InProgress phase.

---

For the Velero CRs we make use of, I haven't seen heavy use of conditions to convey information about errors etc.

Here's the [Velero Backup CRD status section](https://github.com/vmware-tanzu/velero/blob/main/config/crd/bases/velero.io_backups.yaml#L362-L446). I think the phase is the best summary of high level status available on Backups:

```
              - New
              - FailedValidation
              - InProgress
              - Completed
              - PartiallyFailed
              - Failed
              - Deleting
```

If the phase is PartiallyFailed or Failed, we probably want a visual indicator on the Debug View to let the user know they should consider digging deeper. In some cases `PartiallyFailed` can be benign, muddying the waters.

It's maybe worth looking at [each of the Velero CRDs](https://github.com/vmware-tanzu/velero/tree/main/config/crd/bases) to evaluate how information could best be extracted out of them.

---

**Comment by vconzola** [comment]
Rather replicating the information @djwhatle is talking about in the debug view, we should make that part of the enhanced debug reporting we've been talking about but haven't yet put into a sprint. I think the starting point for all of this should be the pipeline. I also think it's going to take an extended period of time where we can all "sit together" and look at what information (CR status, error/warning messages, pod logs, ... I don't know what all) is available for each phase and then decide how to fit it into the UI to provide a useful and meaningful UX.

I don't think is going to be a one day or one sprint effort, especially trying to do this working virtually.

**Comment by djwhatle** [comment]
@ibolton336 I will make you a list of all of the places where we can detect abnormality across the suite of CRs. It differs for each type, so we'll use a switch statement as discussed to determine is a warning or error is present for each.

**Comment by djwhatle** [comment]
**Type: [backups.velero.io](https://github.com/vmware-tanzu/velero/blob/main/config/crd/bases/velero.io_backups.yaml)**

| Status| Indicator(s) |
|---|---|
|⚠️ Warning  | `.status.warnings > 0`, `.status.phase == "PartiallyFailed"`   | 
|❌   Failure     |  `.status.errors > 0`, `.status.phase ==  "Failed"`  |
|✅   Completed  |  `.status.phase = "Completed"`  |
|▶️  Running    |  `.status.phase = "InProgress"`  |

---

**Type: [restores.velero.io](https://github.com/vmware-tanzu/velero/blob/main/config/crd/bases/velero.io_restores.yaml)**

| Status| Indicator(s) |
|---|---|
|⚠️ Warning  | `.status.warnings > 0`, `.status.phase == "PartiallyFailed"`   | 
|❌   Failure     |  `.status.errors > 0`, `.status.phase ==  "Failed"`  |
|✅   Completed  |  `.status.phase = "Completed"`  |
|▶️  Running    |  `.status.phase = "InProgress"`  |

---

**Type: [podvolumebackups.velero.io](https://github.com/vmware-tanzu/velero/blob/main/config/crd/bases/velero.io_podvolumebackups.yaml)**

| Status| Indicator(s) |
|---|---|
|⚠️ Warning  |  `.status.phase == "PartiallyFailed"`   | 
|❌   Failure     | `.status.phase ==  "Failed"`  |
|✅   Completed  |  `.status.phase = "Completed"`  |
|▶️  Running    |  `.status.phase = "InProgress"`  |

---

**Type: [podvolumerestores.velero.io](https://github.com/vmware-tanzu/velero/blob/main/config/crd/bases/velero.io_podvolumerestores.yaml)**

| Status| Indicator(s) |
|---|---|
|⚠️ Warning  |  `.status.phase == "PartiallyFailed"`   | 
|❌   Failure     | `.status.phase ==  "Failed"`  |
|✅   Completed  |  `.status.phase = "Completed"`  |
|▶️  Running    |  `.status.phase = "InProgress"`  |

---

**Type: [directimagemigrations.migration.openshift.io]()**

| Status| Indicator(s) |
|---|---|
|⚠️ Warnings  |  `.status.Conditions[].hasCondition(.category="Critical" or "Error" or "Warn")`  | 
|❌  Failure     |  `.status.Conditions[].hasCondition(.type="Failed")` |
|✅  Completed  |  `.status.Conditions[].hasCondition(.type="Completed")`  |
|▶️ Running    |  `.status.Conditions[].hasCondition(.type="Running")` |

---

**Type: [directvolumemigrations.migration.openshift.io]]()**

| Status| Indicator(s) |
|---|---|
|⚠️ Warnings  |  `.status.Conditions[].hasCondition(.category="Critical" or "Error" or "Warn")`  | 
|❌  Failure     |  `.status.Conditions[].hasCondition(.type="Failed")` |
|✅  Completed  |  `.status.Conditions[].hasCondition(.type="Completed")`  |
|▶️ Running    |  `.status.Conditions[].hasCondition(.type="Running")` |

---

**Type: [directimagestreammigrations.migration.openshift.io]()**

| Status| Indicator(s) |
|---|---|
|⚠️ Warnings  |  `.status.Conditions[].hasCondition(.category="Critical" or "Error" or "Warn")`  | 
|❌  Failure     |  `.status.Conditions[].hasCondition(.type="Failed")` |
|✅  Completed  |  `.status.Conditions[].hasCondition(.type="Completed")`  |
|▶️ Running    |  `.status.Conditions[].hasCondition(.type="Running")` |

---

**Type: [directvolumemigrationprogress.migration.openshift.io]()**

| Status| Indicator(s) |
|---|---|
|⚠️ Warnings  |  `.status.Conditions[].hasCondition(.category="Critical" or "Error" or "Warn")`  | 
|❌  Failure     |  `.status.Conditions[].hasCondition(.type="InvalidPod" or "InvalidPodRef)` |
|✅  Completed  |  n/a   |
|▶️ Running    |  n/a |

---

**Type: [migmigration.migration.openshift.io]()**

| Status| Indicator(s) |
|---|---|
|⚠️ Warnings  |  `.status.Conditions[].hasCondition(.category="Critical" or "Error" or "Warn")`  | 
|❌  Failure     |  `.status.Conditions[].hasCondition(.type="Failed")` |
|✅  Completed  |  `.status.Conditions[].hasCondition(.type="Completed")`  |
|▶️ Running    |  `.status.Conditions[].hasCondition(.type="Running")` |

---

**Type: [miganalytics.migration.openshift.io]()**

| Status| Indicator(s) |
|---|---|
|⚠️ Warnings  |  n/a | 
|❌  Failure     |  n/a |
|✅  Completed  |  `.status.analytics.percentComplete == 100`  |
|▶️ Running    |  `.status.Conditions[].hasCondition(.type="ExtendedPVAnalysisStarted")` |

---

**Review by djwhatle — APPROVED** [review]
LGTM. Thanks for all the work on this Ian, looks great.

**Pull request merged**
