### PR TITLE
Missing Plan wizard plan name invalid helper

### PR DESCRIPTION
**Pull request by gildub**
Closes https://github.com/konveyor/mig-ui/issues/812

invalid-plan

### CODE REVIEW

**Comment by gildub** [comment]
@vconzola, Hi vince the helperTextInvalid is passing the error message from validate function, just checking with you if that message is fine.

**Comment by vconzola** [comment]
@gildub The message is kind of verbose and hard to understand. What's the actual restriction - that a plan name can't contain consecutive special characters?

**Comment by gildub** [comment]
@vconzola, I updated the error message for DNS-1123 labels.

**Comment by gildub** [comment]
@vconzola, please validate lastest change.

**Comment by vconzola** [comment]
@gildub You have an extra space in the middle of the word "characters", but otherwise looks great.

**Comment by gildub** [comment]
@vconzola, thanks for catching it up. It's fixed now.

**Pull request merged**
