### PR TITLE
VolumesForm: Replace Bullseye with Modal to handle critical errors

### PR DESCRIPTION
**Pull request by gildub**
critical

Closes https://github.com/konveyor/mig-ui/issues/756

### CODE REVIEW

**Comment by mturley** [comment]
If I'm reading this code right, when the user clicks the "close" button on that modal it will just leave them with an empty wizard step, right? Maybe we want that button to say "Back" and move the wizard back a step when the modal closes?

**Comment by eriknelson** [comment]
Converted this to a WIP PR since it's not ready. @vconzola do you have some updated mocks for @gildub ?

**Comment by vconzola** [comment]
@gildub The wording might not be exactly right, but this is what we want this sort of message to look like. https://drive.google.com/file/d/1fvzeU0z3LpT3aHUxCHj3mURrXPF37KhO/view?usp=sharing Per PF content guidelines - it's friendly, it explains the issue, and it tells the user what action(s) they should take to resolve the problem.

**Comment by gildub** [comment]
@ibolton336 is this still going to be relevant after non-admin features has been added.

**Comment by mturley** [comment]
@gildub are you still planning to use this PR or should we close it?

**Comment by ibolton336** [comment]
Closing due to lack of activity.

**Pull request closed without merging**
