### PR TITLE
Bug 1929799: Add popover warning for existing hooks in dropdown

### PR DESCRIPTION
**Pull request by ibolton336**
https://bugzilla.redhat.com/show_bug.cgi?id=1929799

### CODE REVIEW

**Comment by ibolton336** [comment]
image

**Review by vconzola — COMMENTED** [review]
I can't read the text in the screenshot, so you might want to run it past Avital. Otherwise, LGTM.

**Comment by ibolton336** [comment]
@vconzola The text reads: This phase cannot be selected because a hook already exists for this phase

**Comment by vconzola** [comment]
@ibolton336 That sounds good to me.

**Pull request merged**
