### PR TITLE
Add search functionality for plans

### PR DESCRIPTION
**Pull request by ibolton336**
Screen Shot 2021-05-18 at 4 53 37 PM

### CODE REVIEW

**Comment by ibolton336** [comment]
@vconzola how does this look?

**Review by vconzola — COMMENTED** [review]
@ibolton336 This is a good start. But since this isn't targeted until 1.6, I'd like to take a deeper look at the use cases where customers (Cisco) are creating hundreds of plans. Are they migrating from/to multiple clusters? Are they using multiple s3 repositories? Are they using some sort of naming conventions for their plans? Any or all of these would indicate a requirement for filtering beyond simple search. @eriknelson your thoughts?

**Comment by ibolton336** [comment]
@vconzola Maybe there is room for another issue capturing that work specifically? This PR was meant to address https://issues.redhat.com/browse/MIG-654

**Comment by vconzola** [comment]
@ibolton336 It's fine if we create another issue, but https://issues.redhat.com/browse/MIG-654 specifically mentions "filter and pagination" in addition to search.

**Comment by pranavgaikwad** [comment]
Tested with about 40 MigPlans in the cluster. Search works, plans are paginated within search results, works as expected!
Peek 2021-07-16 14-13

**Review by pranavgaikwad — APPROVED** [review]

**Comment by ibolton336** [comment]
[mig-654]

**Pull request merged**
