### PR TITLE
Add error modal for cert error/connectivity issues 

### LINKED ISSUE #689: No error message shown when fetching resources fails
Screen Shot 2020-02-20 at 12 20 32 PM

When a session token (https://docs.openshift.com/container-platform/3.3/rest_api/index.html#rest-api-session-tokens) is expired, there is no visual indicator that this has occurred. The fetch polls for resources fail silently in the background and nothing is communicated to the user. This scenario also applies when resource fetch fails for any reason. I turned off my wifi to simulate a loss of connection and this was the result:

Screen Shot 2020-02-21 at 11 07 18 AM

### PR DESCRIPTION
**Pull request by ibolton336**
Closes #689

### CODE REVIEW

**Comment by ibolton336** [comment]
cert-error

**Comment by ibolton336** [comment]
connectivity-error

**Comment by vconzola** [comment]
@ibolton336 Please implement as shown in the mockups, including button layout, colors and icons.

**Comment by ibolton336** [comment]
image
Updated @vconzola

**Comment by vconzola** [comment]
@eriknelson Ack.

**Comment by ibolton336** [comment]
> @eriknelson Ack.

Thanks @vconzola  :+1:

**Comment by eriknelson** [comment]
Pulling and testing

**Comment by eriknelson** [comment]
Marking DNM, AFAIK this has broken app login. Will catch up with Ian.

**Pull request merged**
