### PR TITLE
Disable rollback button after completion, show "Rollback Succeeded" text

### PR DESCRIPTION
**Pull request by djwhatle**
image
image

### CODE REVIEW

**Review by vconzola — CHANGES_REQUESTED** [review]
Tiny nit. "Succeeded" should be "succeeded". We use sentence case everywhere except in the navigation. One other thing...once rollback is complete Stage, Migrate and Edit should become enabled again.

**Comment by ibolton336** [comment]
I wonder what we can show in the pipeline summary view for rollbacks. 
image

**Comment by vconzola** [comment]
> I wonder what we can show in the pipeline summary view for rollbacks.
> image
> 
> Maybe a spinner that uses the isRollbackPolling boolean as a source?

Does rollback have steps and phases like other migrations? If so, we could use the same pipeline view.

**Comment by ibolton336** [comment]
@vconzola I do not think that is implmented yet. The next priority is getting pipeline steps for Direct Migrations. Not sure where that would fall on the roadmap.

**Comment by vconzola** [comment]
@ibolton336 @djwhatle If we don't have any pipeline information (step/phase) during rollback, then I agree that the best thing to do is to show the spinner icon with the the text "In progress". Unless, of course, we get progress status in which case we should show a progress indicator. But I'm guessing we don't get that either?

**Comment by djwhatle** [comment]
> Tiny nit. "Succeeded" should be "succeeded". We use sentence case everywhere except in the navigation. One other thing...
Let me see what I can do. I have carried over the existing convention that is implemented in the code. What you're saying is that we should change all occurrences of this in the UI.

> once rollback is complete Stage, Migrate and Edit should become enabled again.
This is not feasible for 1.4.0 because it would require significant controller + UI changes and we are at code freeze.

**Comment by djwhatle** [comment]
@ibolton336 @vconzola I agree with you that we should fix the pipeline view for rollbacks (tracking in [812](https://github.com/konveyor/mig-controller/issues/812) but that is a separate concern from this PR in my opinion, so I will fix the capitalization error that Vince mentioned here but leave the other problems to be solved in a different PR.

**Comment by djwhatle** [comment]
@ibolton336 @vconzola changed the case as suggested.

**Comment by ibolton336** [comment]
Looks great - thanks @djwhatle

**Review by ibolton336 — APPROVED** [review]
LGTM 💯

**Comment by vconzola** [comment]
@djwhatle If we can't re-enable the Stage, Migrate, and Edit buttons for a plan that's been rolled back what's the status of that plan? Is it just orphaned? I'm not sure why someone would rollback a plan, but can assume it's because something was wrong in the plan configuration. Editing and retrying the plan would seem like obvious next steps. What am I missing in my logic?

**Comment by djwhatle** [comment]
> @djwhatle If we can't re-enable the Stage, Migrate, and Edit buttons for a plan that's been rolled back what's the status of that plan? Is it just orphaned? I'm not sure why someone would rollback a plan, but can assume it's because something was wrong in the plan configuration. Editing and retrying the plan would seem like obvious next steps. What am I missing in my logic?

You could rollback because something was wrong in plan config, or because the migration was unsuccessful and changes need to be reverted. Right now, if you complete a rollback the plan will be in a terminal state, meaning that you should delete the plan and start over.

**Comment by vconzola** [comment]
@djwhatle Thanks for the detailed explanation. I'll talk to @eriknelson about getting these Retry changes into a post 1.4 release because having to recreate a plan every time is kinda ug-ly from a UX standpoint.

**Comment by apinnick** [comment]
> Tiny nit. "Succeeded" should be "succeeded". We use sentence case everywhere except in the navigation. One other 

@vconzola Patternfly4 updated their guidelines. Now they use sentence case in navigation. https://www.patternfly.org/v4/ux-writing/capitalization

**Comment by vconzola** [comment]
@apinnick General PF guidance is sentence case in navigation, however, cloud.redhat.com is an exception in that they're using title case for nav. And since all of our migration apps will eventually live on c.rh.c, I want to follow the same pattern.

**Comment by apinnick** [comment]
> @apinnick General PF guidance is sentence case in navigation, however, cloud.redhat.com is an exception in that they're using title case for nav. And since all of our migration apps will eventually live on c.rh.c, I want to follow the same pattern.

Life is never simple. :-) 
Good to know that cloud portal is an exception.

**Pull request merged**
