### PR TITLE
MIG-119 : Drill down page for migration steps

### PR DESCRIPTION
**Pull request by pranavgaikwad**
Fixes: #1041 

This PR:
- Depends on @ibolton336's PR #1053 
- Adds new drill down page for Migration "steps" details 
- Adds helpers to parse progress messages as reported in MigMigration Status
- Adds progress bars for Velero Backup / Volume Backups and Volume Restores
- Fixes minor issues with the pipeline summary view
- Fixes minor issues with the breadcrumbs in the drill down pages

ui_3

**Note** This pr doesn't address the Warning conditions on completed migmigrations. Ideally, PipelineSummaryView should turn orange and the message should say "Completed with warnings".

### CODE REVIEW

**Comment by eriknelson** [comment]
FYI, we only need the `[MIG-XXX]` tag on issues, not on PRs.

**Comment by ibolton336** [comment]
This also closes https://github.com/konveyor/mig-ui/issues/1041

**Review by vconzola — COMMENTED** [review]
The breadcrumb text and page headings are messed up, but those are things that can be fixed as BZs post 1.4. Otherwise, LGTM.

**Comment by ibolton336** [comment]
Just tested & its working great @pranavgaikwad . Nice work. Maybe in the future we can figure out a way to cache results when navigating throughout the breadcrumb nav.

**Review by ibolton336 — APPROVED** [review]
LGTM! 👍

**Comment by pranavgaikwad** [comment]
@vconzola Happy to fix them right here in this PR. Is there anything specific you want to point out?

**Review by ibolton336 — APPROVED** [review]
LGTM

**Pull request merged**
