### PR TITLE
Move devDependencies over to main deps

### PR DESCRIPTION
**Pull request by ibolton336**
Fixes the build error resulting from using yarn --production flag in docker file.

### CODE REVIEW

**Review by rayfordj — APPROVED** [review]
/lgtm

**Comment by mturley** [comment]
Hmm, @ibolton336 should we review the rest of the devDependencies to see if anything else needs to be moved over? I can imagine something like that sneaking up on us at run time

**Comment by ibolton336** [comment]
> Hmm, @ibolton336 should we review the rest of the devDependencies to see if anything else needs to be moved over? I can imagine something like that sneaking up on us at run time Edit: gave them a once-over and nothing else jumps out at me

@mturley I did a quick check and built images to test. Looked like those were the only two that were causing the image to fail to build. You're instinct to check further gaps is spot on though. Not sure if some other functionality would maybe lazy load during run time like you mentioned. I just looked through the main.js entry point file.

**Comment by mturley** [comment]
I looked at each of the dependencies left in that list and looked up the ones I didn't recognize, they're all of the build/lint/test/mock variety. I think we're probably good.

**Pull request merged**
