### PR TITLE
Add version display and validation support in UI 

### PR DESCRIPTION
**Pull request by ibolton336**

### CODE REVIEW

**Comment by ibolton336** [comment]
image

image

**Comment by ibolton336** [comment]
image

image

**Comment by ibolton336** [comment]
image

**Comment by ibolton336** [comment]
image

**Comment by ibolton336** [comment]
image

**Review by djwhatle — APPROVED** [review]
LGTM visually, assuming UI is doing a `Warn` that allows the user to proceed on migrations despite the version difference when any of these mismatch conditions are encountered (missing key, mismatched version)

**Pull request merged**
