### PR TITLE
Show which cluster a resource is on in the debug view

### PR DESCRIPTION
**Pull request by djwhatle**
Merge with https://github.com/konveyor/mig-controller/pull/1093

image

image

### CODE REVIEW

**Review by vconzola — CHANGES_REQUESTED** [review]
@djwhatle This looks good except the popover icon should follow the guidelines here: https://www.patternfly.org/v4/components/popover/design-guidelines.

**Comment by djwhatle** [comment]
> @djwhatle This looks good except the popover icon should follow the guidelines here: https://www.patternfly.org/v4/components/popover/design-guidelines.

The popover isn't new, I just added a sentence. Could you explain what the delta is between the screenshot I posted and guidelines?

**Comment by vconzola** [comment]
Wrong icon and wrong color. It should be as shown in the first example under "Usage" - the outline version of the icon and colors should be as specific in the example for default, hover, and selected states.

**Comment by djwhatle** [comment]
@vconzola styling fixed 

image

**Review by ibolton336 — APPROVED** [review]
Looking good!

**Pull request merged**
